### ISSUE TITLE
reactivate_user incorrectly sets the content-type for the FusionAuth User API

### ISSUE THREAD

**Issue by jaywood128** [FusionAuth/fusionauth-ruby-client#9]
When attempting to re-activate a user, the library returns the following error:

`#<OpenStruct fieldErrors=#<OpenStruct>, generalErrors=[#<OpenStruct code="[InvalidContentType]", message="Invalid [Content-Type] HTTP request header value of [application/x-www-form-urlencoded]. Supported values for this request include [application/json].">]>`

version `1.42.0` 

Steps to recreate:

1. Follow this guide to getting setup: https://fusionauth.io/docs/v1/tech/client-libraries/ruby
2. Call deactivate, which should work correctly
3. Call reactivate, which should result in the following error above. 

Code snippet:
```
require 'fusionauth/fusionauth_client'

# Construct the FusionAuth Client
client = FusionAuth::FusionAuthClient.new(
    'xxxxxxxxxxx', 
    'http://localhost:9011'
)

# # Deactivate a user
user_id = '123'
response = client.deactivate_user(user_id)

# Reactivate a user
response = client.reactivate_user(user_id)`
```
Solution:

FusionAuth should correctly handle the Content-Type for this method so no error is returned, perhaps defaulting to 'application/json`.

**Comment by doubleswirve** [comment]
Re: @robotdan's patch @ https://github.com/FusionAuth/fusionauth-ruby-client/pull/10#issuecomment-1407089237, this is working for us now! 🎉 Thx so much!
